name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge develop -> Release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: Release
          github_token: ${{ github.token }}

      - name: Merge Release -> Releasedemo
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: Releasedemo
          github_token: ${{ github.token }}
