# This is a basic workflow to help you get started with Actions

name: 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # EMAIL NOTIFICATION
      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
           # mail server settings
           server_address: smtp.gmail.com
           server_port: 465
           # user credentials
           username: ${{secrets.EMAIL_USERNAME}} 
           password: ${{secrets.EMAIL_PASSWORD}}
           # email subject
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
           # email body as text
           body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
           to: arvind.dash555@gmail.com
          # from email name
           from: Arvind Dash
    




      
